/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Colegio.Materia;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Ana luz
 */
public class FrMateria extends javax.swing.JInternalFrame {
 private HashSet <Materia> materiasTotal;
    /**
     * Creates new form frMateria
     */
    public FrMateria(HashSet <Materia> materiasTotal) {
        initComponents();
        this.materiasTotal=materiasTotal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtId = new javax.swing.JTextField();
        jtNombreMateria = new javax.swing.JTextField();
        jtAño = new javax.swing.JTextField();
        jtGuardar = new javax.swing.JButton();
        jtNuevo = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 255, 204));

        jLabel1.setText("Formulario Materias ");

        jLabel2.setText("ID");

        jLabel3.setText("Nombre de la materia");

        jLabel4.setText("Año al que pertenece");

        jtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtIdFocusLost(evt);
            }
        });
        jtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtIdActionPerformed(evt);
            }
        });

        jtNombreMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreMateriaActionPerformed(evt);
            }
        });

        jtAño.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtAñoFocusLost(evt);
            }
        });
        jtAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtAñoActionPerformed(evt);
            }
        });

        jtGuardar.setText("Guardar");
        jtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtGuardarActionPerformed(evt);
            }
        });

        jtNuevo.setText("Nuevo");
        jtNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNuevoActionPerformed(evt);
            }
        });

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtNombreMateria))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtAño))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jtGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 154, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jtNuevo)
                    .addComponent(jtGuardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtIdActionPerformed

    private void jtNombreMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreMateriaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtNombreMateriaActionPerformed

    private void jtAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtAñoActionPerformed

    private void jtNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNuevoActionPerformed
        jtId.setText("");
        jtNombreMateria.setText("");
        jtAño.setText("");
        
        
    }//GEN-LAST:event_jtNuevoActionPerformed

    private void jtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtGuardarActionPerformed
       String nombre = jtNombreMateria.getText();
       int id = Integer.parseInt(jtId.getText());
       int año =Integer.parseInt(jtAño.getText());
       
       try{
          id = Integer.parseInt(jtId.getText());
       }catch(Exception ee){
           JOptionPane.showMessageDialog(this,"El ID de la materia ingresado es incorrecto, por favor ingrese uno nuevo");
           jtNombreMateria.requestFocus();
           
       }
         try{
          año =Integer.parseInt(jtAño.getText());
       }catch(Exception ee){
           JOptionPane.showMessageDialog(this,"El ID de la materia ingresado es incorrecto, por favor ingrese uno nuevo");
           jtNombreMateria.requestFocus();
           
       }

       Materia m = new Materia (id,nombre,año);
       materiasTotal.add(m);
       this.setVisible(false);
       
        
    }//GEN-LAST:event_jtGuardarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtIdFocusLost
        // TODO add your handling code here:
        try{//enciero en un try para que si se escribiera una letra automaticamente se capte la exepcion y se imprima el cartel
             int id = Integer.parseInt(jtId.getText());
                     
        }catch (NumberFormatException nm){
            JOptionPane.showMessageDialog(this,"Debe ingresar solo numeros.");
            jtId.requestFocus();//para que se centre el foco aca y no deje avanzar a los siguientes text fild
        }
    }//GEN-LAST:event_jtIdFocusLost

    private void jtAñoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtAñoFocusLost
        // TODO add your handling code here:
        try{//enciero en un try para que si se escribiera una letra automaticamente se capte la exepcion y se imprima el cartel
             int año = Integer.parseInt(jtAño.getText());
                     
        }catch (NumberFormatException nl){
            JOptionPane.showMessageDialog(this,"Debe ingresar solo numeros.");
            jtAño.requestFocus();//para que se centre el foco aca y no deje avanzar a los siguientes text fild
        }
    }//GEN-LAST:event_jtAñoFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jtAño;
    private javax.swing.JButton jtGuardar;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextField jtNombreMateria;
    private javax.swing.JButton jtNuevo;
    // End of variables declaration//GEN-END:variables
}
